title: Media Stack
theme: dark
color: slate
headerStyle: clean
language: fr
layout:
  Media:
    style: row
    columns: 3
  Downloads:
    style: row
    columns: 2
  Système:
    style: row
    columns: 1
  Calendrier:
    style: column
    columns: 1
  Bookmarks:
    style: row
    columns: 4
