- search:
    provider: overseerr
    target: _blank
    url: https://overseerr.{{HOMEPAGE_VAR_DOMAIN}}

- resources:
    cpu: true
    memory: true
    disk: /

- calendar:
    firstDayInWeek: monday
    view: monthly
    maxEvents: 10
    showTime: true
    integrations:
      - type: sonarr
        service_group: Media
        service_name: Sonarr
      - type: radarr
        service_group: Media
        service_name: Radarr
