- search:
    provider: overseerr
    target: _blank
    url: https://seerr.{{HOMEPAGE_VAR_DOMAIN}}

- resources:
    cpu: true
    memory: true
    disk: /
- resources:
    disk: {{HOMEPAGE_VAR_HETZNER_VOLUME_PATH}}

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
